# Dynamic provisioning on AWS EKS (EBS CSI driver). PVCs using this class get a disk automatically.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-fast
provisioner: ebs.csi.aws.com
parameters: {type: gp3}
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
