apiVersion: v1
kind: Pod
metadata:
  name: init-test

spec:
  initContainers:
  - name: init-container
    image: busybox:latest
    command: ['sh', '-c', 'echo The app is running! && sleep 10; echo Init container completed']

  containers:
  - name: main-container
    image: busybox:latest
    command: ['sh', '-c', 'echo The main container is running! && sleep 3600']